---
# Grab correct vars from either vars/OS or defaults
- include_vars: "{{ item }}"
  with_first_found:
   - "../vars/{{ ansible_distribution }}.yml"
   - "../vars/{{ ansible_os_family }}.yml"
   - "../defaults/main.yml"

- name: Insert sshd_config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0600
  notify: restart ssh
